USE [master]
GO

/****** Object:  Database [qlbanhang]    Script Date: 6/5/2020 6:05:43 PM ******/
CREATE DATABASE [qlbanhang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'qlbanhang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\qlbanhang.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'qlbanhang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\qlbanhang_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [qlbanhang] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qlbanhang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [qlbanhang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [qlbanhang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [qlbanhang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [qlbanhang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [qlbanhang] SET ARITHABORT OFF 
GO

ALTER DATABASE [qlbanhang] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [qlbanhang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [qlbanhang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [qlbanhang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [qlbanhang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [qlbanhang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [qlbanhang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [qlbanhang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [qlbanhang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [qlbanhang] SET  DISABLE_BROKER 
GO

ALTER DATABASE [qlbanhang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [qlbanhang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [qlbanhang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [qlbanhang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [qlbanhang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [qlbanhang] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [qlbanhang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [qlbanhang] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [qlbanhang] SET  MULTI_USER 
GO

ALTER DATABASE [qlbanhang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [qlbanhang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [qlbanhang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [qlbanhang] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [qlbanhang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [qlbanhang] SET  READ_WRITE 
GO

